name: Build and Push Golang Docker Image

on:
  # Trigger only when a tag that starts with a digit is pushed (e.g., 1.0.0)
  push:
    tags:
      - "[0-9]*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: docker-hub

    steps:
      # 1. Check out the repository.
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Go (Optional: only needed if you need to build the binary).
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      # 3. Build Go binary (adjust command based on your project)
      - name: Build Go Application
        run: go build -o app

      # 4. Extract Docker metadata (Get tag from Git and use it for Docker tag)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/example-app
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: steps.docker_login.outcome == 'success'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
